version: '3.9'
services:
  pipd-app:
    build: .
    volumes:
      - ..:/pipd
    ports:
      - 8000:8000
    container_name: pipd-app
  pipd-db:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    container_name: pipd-db
